import * as THREE from 'three';
import type { Version } from './types';

export const SIM_RESOLUTION = 256;
export const PRESSURE_ITERATIONS = 20;
export const REACTION_DIFFUSION_ITERATIONS = 10;
export const PARTICLE_RESOLUTION = 256;

export const versions: Version[] = [
    {
        name: 'Neo Water',
        uniforms: {
            uArtisticBlend: 0.0,
            uDisplacementScale: 0.12,
            uVelocityShiftScale: 0.002,
            uDensityShiftScale: 0.002,
            uWaterColor: new THREE.Color(0.7, 0.85, 0.95),
            uInkColor: new THREE.Color(0.8, 0.9, 1.0),
            uVolumeFactor: 0.15,
            uInkStrength: 0.8,
            uShininess: 300.0,
            uFresnelColor: new THREE.Color(1.0, 1.0, 1.0),
            uFresnelIntensity: 3.0,
            uGlowColor: new THREE.Color(0.8, 0.9, 1.0),
            uGlowPower: 2.0,
            uInkGeneration: 0.05,
            uWaveSize: 0.1,
            uWaveSteepness: 0.1,
            uWaveComplexity: 0.01,
            uWaveDetail: 0.008,
            uFeedRate: 0.0,
            uKillRate: 0.0,
            uVorticity: 15.0,
            uReactionForce: 0.0,
            uBuoyancy: 0.0,
            uAmbientTemperature: 0.0,
            uSplatTemperature: 0.0,
            uBorderThickness: 0.0,
            uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
            uSurfaceTension: 0.2,
            uChiselStrength: 1.5,
            uSSR_Strength: 0.8,
            uSSR_Falloff: 2.5,
            uSSR_Samples: 12,
            uParticleRate: 0.0,
            uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
            uCausticsIntensity: 5.0,
            uLightDepth: 0.7,
            uSurfaceDetailStrength: 0.4,
            uFlowSpeed: 5.0,
            uRippleStrength: 1.2,
            uRippleDamping: 0.995,
            uRippleSpeed: 1.2,
            uLight1Pos: new THREE.Vector3(0.9, 0.9, 0.5),
            uLight1Color: new THREE.Color(1.0, 1.0, 1.0),
            uLight2Pos: new THREE.Vector3(0.1, 0.1, 0.5),
            uLight2Color: new THREE.Color(0.2, 0.5, 1.0),
        },
        simParams: { velocityDissipation: 0.99, densityDissipation: 0.98, temperatureDissipation: 0.98 }
    },
    {
        name: 'Mercury',
        uniforms: {
            uArtisticBlend: 0.1,
            uDisplacementScale: 0.1,
            uVelocityShiftScale: 0.0005,
            uDensityShiftScale: 0.0005,
            uWaterColor: new THREE.Color(0.15, 0.18, 0.2),
            uInkColor: new THREE.Color(1.0, 1.0, 1.0),
            uVolumeFactor: 1.0,
            uInkStrength: 6.0,
            uShininess: 1000.0,
            uFresnelColor: new THREE.Color(0.9, 0.95, 1.0),
            uFresnelIntensity: 4.0,
            uGlowColor: new THREE.Color(0.8, 0.9, 1.0),
            uGlowPower: 1.0,
            uInkGeneration: 0.0,
            uWaveSize: 0.08,
            uWaveSteepness: 0.15,
            uWaveComplexity: 0.0,
            uWaveDetail: 0.0,
            uFeedRate: 0.0,
            uKillRate: 0.0,
            uVorticity: 0.0,
            uReactionForce: 0.0,
            uBuoyancy: 0.0,
            uAmbientTemperature: 0.0,
            uSplatTemperature: 0.0,
            uBorderThickness: 0.0,
            uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
            uSurfaceTension: 1.5,
            uChiselStrength: 3.0,
            uSSR_Strength: 2.5,
            uSSR_Falloff: 1.5,
            uSSR_Samples: 25,
            uParticleRate: 0.0,
            uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
            uCausticsIntensity: 0.0,
            uLightDepth: 0.1,
            uSurfaceDetailStrength: 0.8,
            uFlowSpeed: 1.0,
            uRippleStrength: 0.4,
            uRippleDamping: 0.95,
            uRippleSpeed: 0.2,
            uLight1Pos: new THREE.Vector3(1.0, 1.0, 0.8),
            uLight1Color: new THREE.Color(1.0, 1.0, 1.0),
            uLight2Pos: new THREE.Vector3(-0.5, -0.5, 0.5),
            uLight2Color: new THREE.Color(0.5, 0.5, 0.5),
        },
        simParams: { velocityDissipation: 0.98, densityDissipation: 0.96, temperatureDissipation: 0.98 }
    },
    {
        name: 'Crystal Clear',
        uniforms: {
            uArtisticBlend: 0.0,
            uDisplacementScale: 0.058,
            uVelocityShiftScale: 0.001,
            uDensityShiftScale: 0.0059,
            uWaterColor: new THREE.Color(0.6, 0.8, 0.9),
            uInkColor: new THREE.Color(0.8, 0.9, 1.0),
            uVolumeFactor: 0.81,
            uInkStrength: 0.55,
            uShininess: 92.0,
            uFresnelColor: new THREE.Color(1.0, 1.0, 1.0),
            uFresnelIntensity: 2.1,
            uGlowColor: new THREE.Color(0.8, 0.9, 1.0),
            uGlowPower: 1.8,
            uInkGeneration: 0.02,
            uWaveSize: 0.12,
            uWaveSteepness: 0.08,
            uWaveComplexity: 0.028,
            uWaveDetail: 0.033,
            uFeedRate: 0.017,
            uKillRate: 0.036,
            uVorticity: 0.0,
            uReactionForce: 0.14,
            uBuoyancy: 0.22,
            uAmbientTemperature: 0.0,
            uSplatTemperature: 0.0,
            uBorderThickness: 0.05,
            uBorderColor: new THREE.Color(0.1, 0.1, 0.1),
            uSurfaceTension: 0.06,
            uChiselStrength: 3.0,
            uSSR_Strength: 0.0,
            uSSR_Falloff: 2.8,
            uSSR_Samples: 0,
            uParticleRate: 0.0,
            uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
            uCausticsIntensity: 0.1,
            uLightDepth: 0.6,
            uSurfaceDetailStrength: 0.04,
            uFlowSpeed: 0.9,
            uRippleStrength: 1.0,
            uRippleDamping: 0.913,
            uRippleSpeed: 1.0,
            uLight1Pos: new THREE.Vector3(0.5, 0.5, 0.6),
            uLight1Color: new THREE.Color(0.8, 0.9, 1.0),
            uLight2Pos: new THREE.Vector3(-0.5, -0.5, 0.4),
            uLight2Color: new THREE.Color(0.5, 0.8, 1.0),
        },
        simParams: { velocityDissipation: 0.856, densityDissipation: 0.927, temperatureDissipation: 0.88 }
    },
    {
        name: 'Sora',
        uniforms: {
            uArtisticBlend: 0.0,
            uDisplacementScale: 0.055,
            uVelocityShiftScale: 0.0006,
            uDensityShiftScale: 0.0042,
            uWaterColor: new THREE.Color(0.02, 0.0, 0.05),
            uInkColor: new THREE.Color(0.7, 0.4, 1.0),
            uVolumeFactor: 0.67,
            uInkStrength: 1.5,
            uShininess: 615.0,
            uFresnelColor: new THREE.Color(1.0, 0.6, 0.8),
            uFresnelIntensity: 3.5,
            uGlowColor: new THREE.Color(0.8, 0.4, 1.0),
            uGlowPower: 0.6,
            uInkGeneration: 0.05,
            uWaveSize: 0.157,
            uWaveSteepness: 0.119,
            uWaveComplexity: 0.014,
            uWaveDetail: 0.008,
            uFeedRate: 0.023,
            uKillRate: 0.028,
            uVorticity: 0.4,
            uReactionForce: 0.3,
            uBuoyancy: 2.0,
            uAmbientTemperature: 0.28,
            uSplatTemperature: 0.0,
            uBorderThickness: 0.0,
            uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
            uSurfaceTension: 0.84,
            uChiselStrength: 2.97,
            uSSR_Strength: 0.05,
            uSSR_Falloff: 4.3,
            uSSR_Samples: 2,
            uParticleRate: 0.0,
            uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
            uCausticsIntensity: 3.2,
            uLightDepth: 0.4,
            uSurfaceDetailStrength: 0.01,
            uFlowSpeed: 8.0,
            uRippleStrength: 1.52,
            uRippleDamping: 0.917,
            uRippleSpeed: 1.26,
            uLight1Pos: new THREE.Vector3(0.8, 0.2, 0.7),
            uLight1Color: new THREE.Color(0.8, 0.4, 1.0),
            uLight2Pos: new THREE.Vector3(0.2, 0.8, 0.3),
            uLight2Color: new THREE.Color(0.0, 0.0, 0.0),
        },
        simParams: { velocityDissipation: 0.976, densityDissipation: 0.88, temperatureDissipation: 0.885 }
    },
    {
        name: 'Rainbow Flare',
        uniforms: {
            uArtisticBlend: 0.8,
            uDisplacementScale: 0.08,
            uVelocityShiftScale: 0.01,
            uDensityShiftScale: 0.04,
            uWaterColor: new THREE.Color(0.05, 0.0, 0.1),
            uInkColor: new THREE.Color(1.0, 1.0, 1.0),
            uVolumeFactor: 0.3,
            uInkStrength: 1.8,
            uShininess: 80.0,
            uFresnelColor: new THREE.Color(1.0, 0.7, 1.0),
            uFresnelIntensity: 3.0,
            uGlowColor: new THREE.Color(0.8, 0.9, 1.0),
            uGlowPower: 4.0,
            uInkGeneration: 0.05,
            uWaveSize: 0.1,
            uWaveSteepness: 0.06,
            uWaveComplexity: 0.01,
            uWaveDetail: 0.0,
            uFeedRate: 0.0,
            uKillRate: 0.0,
            uVorticity: 5.0,
            uReactionForce: 0.0,
            uBuoyancy: 0.0,
            uAmbientTemperature: 0.0,
            uSplatTemperature: 0.0,
            uBorderThickness: 0.0,
            uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
            uSurfaceTension: 0.2,
            uChiselStrength: 1.5,
            uSSR_Strength: 0.2,
            uSSR_Falloff: 2.0,
            uSSR_Samples: 5,
            uParticleRate: 0.8,
            uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
            uCausticsIntensity: 0.2,
            uLightDepth: 0.5,
            uSurfaceDetailStrength: 0.05,
            uFlowSpeed: 2.0,
            uRippleStrength: 0.25,
            uRippleDamping: 0.985,
            uRippleSpeed: 0.5,
            uLight1Pos: new THREE.Vector3(0.0, 0.5, 0.5),
            uLight1Color: new THREE.Color(1.0, 0.2, 0.2),
            uLight2Pos: new THREE.Vector3(1.0, 0.5, 0.5),
            uLight2Color: new THREE.Color(0.2, 0.2, 1.0),
        },
        simParams: { velocityDissipation: 0.985, densityDissipation: 0.99, temperatureDissipation: 0.98 }
    },
    {
        name: 'Living Ink',
        uniforms: {
            uArtisticBlend: 0.2,
            uDisplacementScale: 0.06,
            uVelocityShiftScale: 0.005,
            uDensityShiftScale: 0.01,
            uWaterColor: new THREE.Color(0.0, 0.01, 0.02),
            uInkColor: new THREE.Color(0.0, 1.0, 0.7),
            uVolumeFactor: 0.5,
            uInkStrength: 2.5,
            uShininess: 150.0,
            uFresnelColor: new THREE.Color(0.2, 1.0, 0.7),
            uFresnelIntensity: 2.0,
            uGlowColor: new THREE.Color(0.0, 0.7, 1.0),
            uGlowPower: 3.0,
            uInkGeneration: 0.0,
            uWaveSize: 0.1,
            uWaveSteepness: 0.05,
            uWaveComplexity: 0.1,
            uWaveDetail: 0.005,
            uFeedRate: 0.037,
            uKillRate: 0.06,
            uVorticity: 30.0,
            uReactionForce: 0.8,
            uBuoyancy: 0.05,
            uAmbientTemperature: 0.0,
            uSplatTemperature: 0.01,
            uBorderThickness: 0.0,
            uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
            uSurfaceTension: 0.5,
            uChiselStrength: 1.2,
            uSSR_Strength: 0.8,
            uSSR_Falloff: 2.5,
            uSSR_Samples: 8,
            uParticleRate: 0.0,
            uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
            uCausticsIntensity: 0.0,
            uLightDepth: 0.5,
            uSurfaceDetailStrength: 0.1,
            uFlowSpeed: 5.0,
            uRippleStrength: 0.1,
            uRippleDamping: 0.97,
            uRippleSpeed: 0.4,
            uLight1Pos: new THREE.Vector3(0.5, 1.0, 0.6),
            uLight1Color: new THREE.Color(0.0, 1.0, 0.7),
            uLight2Pos: new THREE.Vector3(0.5, 0.0, 0.4),
            uLight2Color: new THREE.Color(1.0, 1.0, 1.0),
        },
        simParams: { velocityDissipation: 0.99, densityDissipation: 0.998, temperatureDissipation: 0.99 }
    },
    {
        name: 'Luminous Gel',
        uniforms: {
            uArtisticBlend: 1.0,
            uDisplacementScale: 0.05,
            uVelocityShiftScale: 0.006,
            uDensityShiftScale: 0.03,
            uWaterColor: new THREE.Color(0.4, 0.0, 0.15),
            uInkColor: new THREE.Color(1.0, 0.8, 0.9),
            uVolumeFactor: 0.8,
            uInkStrength: 2.0,
            uShininess: 120.0,
            uFresnelColor: new THREE.Color(1.0, 0.9, 0.2),
            uFresnelIntensity: 2.5,
            uGlowColor: new THREE.Color(1.0, 0.1, 0.3),
            uGlowPower: 3.0,
            uInkGeneration: 0.1,
            uWaveSize: 0.08,
            uWaveSteepness: 0.04,
            uWaveComplexity: 0.0,
            uWaveDetail: 0.0,
            uFeedRate: 0.0,
            uKillRate: 0.0,
            uVorticity: 0.0,
            uReactionForce: 0.0,
            uBuoyancy: 0.0,
            uAmbientTemperature: 0.0,
            uSplatTemperature: 0.0,
            uBorderThickness: 0.0,
            uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
            uSurfaceTension: 0.8,
            uChiselStrength: 2.0,
            uSSR_Strength: 0.0,
            uSSR_Falloff: 1.0,
            uSSR_Samples: 0,
            uParticleRate: 0.0,
            uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
            uCausticsIntensity: 0.1,
            uLightDepth: 0.3,
            uSurfaceDetailStrength: 0.05,
            uFlowSpeed: 1.0,
            uRippleStrength: 0.05,
            uRippleDamping: 0.92,
            uRippleSpeed: 0.1,
            uLight1Pos: new THREE.Vector3(0.7, 0.7, 0.4),
            uLight1Color: new THREE.Color(1.0, 0.1, 0.3),
            uLight2Pos: new THREE.Vector3(0.3, 0.3, 0.6),
            uLight2Color: new THREE.Color(1.0, 0.9, 0.2),
        },
        simParams: { velocityDissipation: 0.96, densityDissipation: 0.97, temperatureDissipation: 0.98 }
    },
    {
        name: 'Liquid Chrome',
        uniforms: {
            uArtisticBlend: 0.15,
            uDisplacementScale: 0.15,
            uVelocityShiftScale: 0.001,
            uDensityShiftScale: 0.002,
            uWaterColor: new THREE.Color(0.05, 0.05, 0.08),
            uInkColor: new THREE.Color(1.0, 1.0, 1.0),
            uVolumeFactor: 0.6,
            uInkStrength: 3.0,
            uShininess: 250.0,
            uFresnelColor: new THREE.Color(0.9, 0.95, 1.0),
            uFresnelIntensity: 3.5,
            uGlowColor: new THREE.Color(0.4, 0.6, 1.0),
            uGlowPower: 3.0,
            uInkGeneration: 0.1,
            uWaveSize: 0.1,
            uWaveSteepness: 0.12,
            uWaveComplexity: 0.01,
            uWaveDetail: 0.005,
            uFeedRate: 0.0,
            uKillRate: 0.0,
            uVorticity: 20.0,
            uReactionForce: 0.0,
            uBuoyancy: 0.0,
            uAmbientTemperature: 0.0,
            uSplatTemperature: 0.0,
            uBorderThickness: 0.0,
            uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
            uSurfaceTension: 1.2,
            uChiselStrength: 2.5,
            uSSR_Strength: 2.0,
            uSSR_Falloff: 1.5,
            uSSR_Samples: 20,
            uParticleRate: 0.0,
            uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
            uCausticsIntensity: 0.0,
            uLightDepth: 0.2,
            uSurfaceDetailStrength: 0.6,
            uFlowSpeed: 1.0,
            uRippleStrength: 0.3,
            uRippleDamping: 0.97,
            uRippleSpeed: 0.6,
            uLight1Pos: new THREE.Vector3(0.2, 0.8, 0.7),
            uLight1Color: new THREE.Color(0.4, 0.6, 1.0),
            uLight2Pos: new THREE.Vector3(0.8, 0.2, 0.3),
            uLight2Color: new THREE.Color(1.0, 1.0, 1.0),
        },
        simParams: { velocityDissipation: 0.985, densityDissipation: 0.99, temperatureDissipation: 0.98 }
    },
     {
        name: 'Thermal',
        uniforms: {
            uArtisticBlend: 0.1,
            uDisplacementScale: 0.1,
            uVelocityShiftScale: 0.003,
            uDensityShiftScale: 0.005,
            uWaterColor: new THREE.Color(0.2, 0.05, 0.0),
            uInkColor: new THREE.Color(1.0, 0.4, 0.1),
            uVolumeFactor: 0.4,
            uInkStrength: 2.0,
            uShininess: 200.0,
            uFresnelColor: new THREE.Color(1.0, 0.6, 0.3),
            uFresnelIntensity: 2.0,
            uGlowColor: new THREE.Color(1.0, 0.3, 0.0),
            uGlowPower: 5.0,
            uInkGeneration: 0.0,
            uWaveSize: 0.08,
            uWaveSteepness: 0.04,
            uWaveComplexity: 0.0,
            uWaveDetail: 0.0,
            uFeedRate: 0.0,
            uKillRate: 0.0,
            uVorticity: 5.0,
            uReactionForce: 0.0,
            uBuoyancy: 1.5,
            uAmbientTemperature: 0.0,
            uSplatTemperature: 0.5,
            uBorderThickness: 0.0,
            uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
            uSurfaceTension: 0.1,
            uChiselStrength: 0.8,
            uSSR_Strength: 0.0,
            uSSR_Falloff: 1.0,
            uSSR_Samples: 0,
            uParticleRate: 0.0,
            uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
            uCausticsIntensity: 0.0,
            uLightDepth: 0.5,
            uSurfaceDetailStrength: 0.1,
            uFlowSpeed: 1.0,
            uRippleStrength: 0.05,
            uRippleDamping: 0.98,
            uRippleSpeed: 0.5,
            uLight1Pos: new THREE.Vector3(0.5, 0.9, 0.5),
            uLight1Color: new THREE.Color(1.0, 0.6, 0.3),
            uLight2Pos: new THREE.Vector3(0.5, 0.1, 0.5),
            uLight2Color: new THREE.Color(1.0, 0.3, 0.0),
        },
        simParams: { velocityDissipation: 0.98, densityDissipation: 0.98, temperatureDissipation: 0.98 }
    },
    {
        name: 'Deep Ocean',
        uniforms: {
            uArtisticBlend: 0.0,
            uDisplacementScale: 0.07,
            uVelocityShiftScale: 0.002,
            uDensityShiftScale: 0.002,
            uWaterColor: new THREE.Color(0.02, 0.08, 0.25),
            uInkColor: new THREE.Color(0.5, 0.8, 1.0),
            uVolumeFactor: 1.0,
            uInkStrength: 4.0,
            uShininess: 40.0,
            uFresnelColor: new THREE.Color(0.2, 0.8, 1.0), uFresnelIntensity: 1.2,
            uGlowColor: new THREE.Color(0.1, 0.4, 0.6), uGlowPower: 2.5,
            uInkGeneration: 0.01,
            uWaveSize: 0.16,
            uWaveSteepness: 0.05,
            uWaveComplexity: 0.05,
            uWaveDetail: 0.0,
            uFeedRate: 0.0,
            uKillRate: 0.0,
            uVorticity: 0.0,
            uReactionForce: 0.0,
            uBuoyancy: 0.0,
            uAmbientTemperature: 0.0,
            uSplatTemperature: 0.0,
            uBorderThickness: 0.0,
            uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
            uSurfaceTension: 0.1,
            uChiselStrength: 0.8,
            uSSR_Strength: 0.0,
            uSSR_Falloff: 1.0,
            uSSR_Samples: 0,
            uParticleRate: 0.0,
            uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
            uCausticsIntensity: 1.5,
            uLightDepth: 0.9,
            uSurfaceDetailStrength: 0.15,
            uFlowSpeed: 2.0,
            uRippleStrength: 0.8,
            uRippleDamping: 0.988,
            uRippleSpeed: 0.4,
            uLight1Pos: new THREE.Vector3(0.5, 1.0, 0.9),
            uLight1Color: new THREE.Color(0.5, 0.8, 1.0),
            uLight2Pos: new THREE.Vector3(0.5, 0.0, 0.1),
            uLight2Color: new THREE.Color(0.1, 0.4, 0.6),
        },
        simParams: { velocityDissipation: 0.99, densityDissipation: 0.99, temperatureDissipation: 0.98 }
    },
    {
        name: 'Molten Metal',
        uniforms: {
            uArtisticBlend: 0.9,
            uDisplacementScale: 0.04,
            uVelocityShiftScale: 0.00025,
            uDensityShiftScale: 0.00025,
            uWaterColor: new THREE.Color(0.1, 0.1, 0.12),
            uInkColor: new THREE.Color(1.0, 0.5, 0.1),
            uVolumeFactor: 0.9,
            uInkStrength: 5.0,
            uShininess: 300.0,
            uFresnelColor: new THREE.Color(0.95, 0.95, 1.0), uFresnelIntensity: 3.0,
            uGlowColor: new THREE.Color(1.0, 0.3, 0.0), uGlowPower: 3.5,
            uInkGeneration: 0.005,
            uWaveSize: 0.06,
            uWaveSteepness: 0.03,
            uWaveComplexity: 0.01,
            uWaveDetail: 0.002,
            uFeedRate: 0.0,
            uKillRate: 0.0,
            uVorticity: 0.0,
            uReactionForce: 0.0,
            uBuoyancy: 0.0,
            uAmbientTemperature: 0.0,
            uSplatTemperature: 0.0,
            uBorderThickness: 0.0,
            uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
            uSurfaceTension: 1.0,
            uChiselStrength: 2.5,
            uSSR_Strength: 1.5,
            uSSR_Falloff: 2.0,
            uSSR_Samples: 15,
            uParticleRate: 0.0,
            uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
            uCausticsIntensity: 0.0,
            uLightDepth: 0.1,
            uSurfaceDetailStrength: 0.4,
            uFlowSpeed: 0.5,
            uRippleStrength: 0.1,
            uRippleDamping: 0.9,
            uRippleSpeed: 0.08,
            uLight1Pos: new THREE.Vector3(0.5, 0.5, 0.4),
            uLight1Color: new THREE.Color(1.0, 0.5, 0.1),
            uLight2Pos: new THREE.Vector3(0.5, 0.5, 0.6),
            uLight2Color: new THREE.Color(1.0, 0.3, 0.0),
        },
        simParams: { velocityDissipation: 0.9, densityDissipation: 0.98, temperatureDissipation: 0.98 }
    },
    {
        name: 'Ethereal Glow',
        uniforms: {
            uArtisticBlend: 1.0,
            uDisplacementScale: 0.12,
            uVelocityShiftScale: 0.004,
            uDensityShiftScale: 0.006,
            uWaterColor: new THREE.Color(0.1, 0.2, 0.25),
            uInkColor: new THREE.Color(0.8, 1.0, 0.9),
            uVolumeFactor: 0.3,
            uInkStrength: 1.0,
            uShininess: 30.0,
            uFresnelColor: new THREE.Color(1.0, 0.6, 0.8), uFresnelIntensity: 2.5,
            uGlowColor: new THREE.Color(0.5, 1.0, 0.8), uGlowPower: 2.0,
            uInkGeneration: 0.2,
            uWaveSize: 0.14,
            uWaveSteepness: 0.09,
            uWaveComplexity: 0.0,
            uWaveDetail: 0.0,
            uFeedRate: 0.0,
            uKillRate: 0.0,
            uVorticity: 0.0,
            uReactionForce: 0.0,
            uBuoyancy: 0.0,
            uAmbientTemperature: 0.0,
            uSplatTemperature: 0.0,
            uBorderThickness: 0.0,
            uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
            uSurfaceTension: 0.05,
            uChiselStrength: 0.5,
            uSSR_Strength: 0.0,
            uSSR_Falloff: 1.0,
            uSSR_Samples: 0,
            uParticleRate: 0.0,
            uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
            uCausticsIntensity: 0.0,
            uLightDepth: 0.5,
            uSurfaceDetailStrength: 0.0,
            uFlowSpeed: 1.0,
            uRippleStrength: 0.2,
            uRippleDamping: 0.985,
            uRippleSpeed: 0.4,
            uLight1Pos: new THREE.Vector3(0.2, 0.8, 0.5),
            uLight1Color: new THREE.Color(0.5, 1.0, 0.8),
            uLight2Pos: new THREE.Vector3(0.8, 0.2, 0.5),
            uLight2Color: new THREE.Color(1.0, 0.6, 0.8),
        },
        simParams: { velocityDissipation: 0.99, densityDissipation: 0.995, temperatureDissipation: 0.98 }
    },
    {
        name: 'Lusion',
        uniforms: {
            uArtisticBlend: 0.1,
            uDisplacementScale: 0.09,
            uVelocityShiftScale: 0.004,
            uDensityShiftScale: 0.012,
            uWaterColor: new THREE.Color(0.01, 0.0, 0.02),
            uInkColor: new THREE.Color(0.3, 0.8, 1.0),
            uVolumeFactor: 0.85,
            uInkStrength: 4.5,
            uShininess: 280.0,
            uFresnelColor: new THREE.Color(0.1, 0.7, 1.0), uFresnelIntensity: 3.0,
            uGlowColor: new THREE.Color(0.2, 0.5, 1.0), uGlowPower: 2.0,
            uInkGeneration: 0.08,
            uWaveSize: 0.09,
            uWaveSteepness: 0.06,
            uWaveComplexity: 0.02,
            uWaveDetail: 0.01,
            uFeedRate: 0.0,
            uKillRate: 0.0,
            uVorticity: 15.0,
            uReactionForce: 0.0,
            uBuoyancy: 0.0,
            uAmbientTemperature: 0.0,
            uSplatTemperature: 0.0,
            uBorderThickness: 0.0,
            uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
            uSurfaceTension: 0.4,
            uChiselStrength: 1.8,
            uSSR_Strength: 0.0,
            uSSR_Falloff: 1.0,
            uSSR_Samples: 0,
            uParticleRate: 0.0,
            uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
            uCausticsIntensity: 0.2,
            uLightDepth: 0.5,
            uSurfaceDetailStrength: 0.1,
            uFlowSpeed: 2.0,
            uRippleStrength: 0.3,
            uRippleDamping: 0.975,
            uRippleSpeed: 0.5,
            uLight1Pos: new THREE.Vector3(0.1, 0.8, 0.5),
            uLight1Color: new THREE.Color(0.1, 0.7, 1.0),
            uLight2Pos: new THREE.Vector3(0.9, 0.2, 0.5),
            uLight2Color: new THREE.Color(0.2, 0.5, 1.0),
        },
        simParams: { velocityDissipation: 0.98, densityDissipation: 0.98, temperatureDissipation: 0.98 }
    },
    {
        name: 'Awwwards',
        uniforms: {
            uArtisticBlend: 0.1,
            uDisplacementScale: 0.15,
            uVelocityShiftScale: 0.01,
            uDensityShiftScale: 0.03,
            uWaterColor: new THREE.Color(0.1, 0.1, 0.1),
            uInkColor: new THREE.Color(0.0, 1.0, 0.8),
            uVolumeFactor: 0.2,
            uInkStrength: 3.0,
            uShininess: 280.0,
            uFresnelColor: new THREE.Color(1.0, 0.0, 1.0),
            uFresnelIntensity: 3.5,
            uGlowColor: new THREE.Color(0.0, 1.0, 0.8),
            uGlowPower: 4.0,
            uInkGeneration: 0.3,
            uWaveSize: 0.15,
            uWaveSteepness: 0.1,
            uWaveComplexity: 0.15,
            uWaveDetail: 0.02,
            uFeedRate: 0.0,
            uKillRate: 0.0,
            uVorticity: 10.0,
            uReactionForce: 0.0,
            uBuoyancy: 0.0,
            uAmbientTemperature: 0.0,
            uSplatTemperature: 0.0,
            uBorderThickness: 0.0,
            uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
            uSurfaceTension: 0.8,
            uChiselStrength: 3.0,
            uSSR_Strength: 0.0,
            uSSR_Falloff: 1.0,
            uSSR_Samples: 0,
            uParticleRate: 0.0,
            uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
            uCausticsIntensity: 0.0,
            uLightDepth: 0.5,
            uSurfaceDetailStrength: 0.1,
            uFlowSpeed: 1.0,
            uRippleStrength: 0.6,
            uRippleDamping: 0.98,
            uRippleSpeed: 0.8,
            uLight1Pos: new THREE.Vector3(0.5, 0.5, 0.5),
            uLight1Color: new THREE.Color(0.0, 1.0, 0.8),
            uLight2Pos: new THREE.Vector3(0.5, 0.5, 0.5),
            uLight2Color: new THREE.Color(1.0, 0.0, 1.0),
        },
        simParams: { velocityDissipation: 0.95, densityDissipation: 0.92, temperatureDissipation: 0.98 }
    },
];