import * as THREE from 'three';
import { Version } from '../types';

export const awwwards: Version = {
    name: 'Awwwards',
    uniforms: {
        uArtisticBlend: 0.1,
        uDisplacementScale: 0.15,
        uVelocityShiftScale: 0.005,
        uDensityShiftScale: 0.015,
        uWaterColor: new THREE.Color(0.1, 0.1, 0.1),
        uInkColor: new THREE.Color(0.0, 1.0, 0.8),
        uVolumeFactor: 0.2,
        uInkStrength: 3.0,
        uShininess: 280.0,
        uFresnelColor: new THREE.Color(1.0, 0.0, 1.0),
        uFresnelIntensity: 3.5,
        uGlowColor: new THREE.Color(0.0, 1.0, 0.8),
        uGlowPower: 4.0,
        uInkGeneration: 0.3,
        uWaveSize: 0.15,
        uWaveSteepness: 0.1,
        uWaveComplexity: 0.15,
        uWaveDetail: 0.02,
        uFeedRate: 0.0,
        uKillRate: 0.0,
        uVorticity: 5.0,
        uReactionForce: 0.0,
        uBuoyancy: 0.0,
        uAmbientTemperature: 0.0,
        uSplatTemperature: 0.0,
        uBorderThickness: 0.0,
        uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
        uSurfaceTension: 0.8,
        uChiselStrength: 3.0,
        uSSR_Strength: 0.0,
        uSSR_Falloff: 1.0,
        uSSR_Samples: 0,
        uParticleRate: 0.0,
        uParticleSize: 2.0,
        uParticleAdvection: 0.2,
        uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
        uCausticsIntensity: 0.0,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0.1,
        uFlowSpeed: 1.0,
        uRippleStrength: 0.9,
        uRippleDamping: 0.98,
        uRippleSpeed: 0.8,
        uLight1Pos: new THREE.Vector3(0.5, 0.5, 0.5),
        uLight1Color: new THREE.Color(0.0, 1.0, 0.8),
        uLight2Pos: new THREE.Vector3(0.5, 0.5, 0.5),
        uLight2Color: new THREE.Color(1.0, 0.0, 1.0),
    },
    simParams: { waveDecay: 0.985, densityDissipation: 0.96, temperatureDissipation: 0.98 }
};
