import * as THREE from 'three';
import { Version } from '../types';

export const liquidBubble: Version = {
    name: 'Liquid Bubble',
    uniforms: {
        uArtisticBlend: 0,
        uDisplacementScale: 0.066,
        uVelocityShiftScale: 0.001,
        uDensityShiftScale: 0.001,
        uWaterColor: "#4d4d4d",
        uInkColor: "#1b3b64",
        uVolumeFactor: 0.72,
        uInkStrength: 1.2,
        uShininess: 500,
        uFresnelColor: "#000000",
        uFresnelIntensity: 3.2,
        uGlowColor: "#f2f2f2",
        uGlowPower: 5.5,
        uInkGeneration: 0.05,
        uWaveSize: 0.156,
        uWaveSteepness: 0.182,
        uWaveComplexity: 0.015,
        uWaveDetail: 0.036,
        uFeedRate: 0.017,
        uKillRate: 0.043,
        uVorticity: 0,
        uReactionForce: 0.64,
        uBuoyancy: 0.07,
        uAmbientTemperature: 0.14,
        uSplatTemperature: 0,
        uBorderThickness: 0,
        uBorderColor: "#fffafa",
        uSurfaceTension: 0.36,
        uChiselStrength: 3.56,
        uSSR_Strength: 0.8,
        uSSR_Falloff: 0.8,
        uSSR_Samples: 1,
        uParticleRate: 0.44,
        uParticleSize: 1.5,
        uParticleAdvection: 0.6,
        uParticleColor: "#ffffff",
        uCausticsIntensity: 0.5,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0.04,
        uFlowSpeed: 0,
        uRippleStrength: 0,
        uRippleDamping: 0.912,
        uRippleSpeed: 0,
        uLight1Pos: new THREE.Vector3(0.8, 1, 0.6),
        uLight1Color: "#eef2ff",
        uLight2Pos: new THREE.Vector3(-0.5, -0.2, 0.4),
        uLight2Color: "#b1b1c3",
    },
    simParams: {
        waveDecay: 0.997,
        densityDissipation: 0.97,
        temperatureDissipation: 0.98
    }
};
