import * as THREE from 'three';
import { Version } from '../types';

export const liquidBubble: Version = {
    name: 'Liquid Bubble',
    uniforms: {
        uArtisticBlend: 0,
        uDisplacementScale: 0.066,
        uVelocityShiftScale: 0.001,
        uDensityShiftScale: 0.001,
        uWaterColor: new THREE.Color("#5a79dd"),
        uInkColor: new THREE.Color("#66aaff"),
        uVolumeFactor: 0.72,
        uInkStrength: 1.2,
        uShininess: 500.0,
        uFresnelColor: new THREE.Color("#000000"),
        uFresnelIntensity: 1.8,
        uGlowColor: new THREE.Color("#cce5ff"),
        uGlowPower: 1.5,
        uInkGeneration: 0.1,
        uWaveSize: 0.156,
        uWaveSteepness: 0.182,
        uWaveComplexity: 0.015,
        uWaveDetail: 0.036,
        uFeedRate: 0.017,
        uKillRate: 0.043,
        uVorticity: 0,
        uReactionForce: 0,
        uBuoyancy: 0.07,
        uAmbientTemperature: 0.14,
        uSplatTemperature: 0,
        uBorderThickness: 0,
        uBorderColor: new THREE.Color("#5153c2"),
        uSurfaceTension: 0.36,
        uChiselStrength: 3.56,
        uSSR_Strength: 0.8,
        uSSR_Falloff: 0.8,
        uSSR_Samples: 1,
        uParticleRate: 0.44,
        uParticleSize: 1.5,
        uParticleAdvection: 0.6,
        uParticleColor: new THREE.Color("#aaddff"),
        uCausticsIntensity: 0.5,
        uLightDepth: 0.7,
        uSurfaceDetailStrength: 0.04,
        uFlowSpeed: 0,
        uRippleStrength: 0.04,
        uRippleDamping: 0.912,
        uRippleSpeed: 0,
        uLight1Pos: new THREE.Vector3(0.8, 1.0, 0.6),
        uLight1Color: new THREE.Color("#ddeeff"),
        uLight2Pos: new THREE.Vector3(-0.5, -0.2, 0.4),
        uLight2Color: new THREE.Color("#223366"),
    },
    simParams: {
        waveDecay: 0.997,
        densityDissipation: 0.97,
        temperatureDissipation: 0.98
    }
};