import * as THREE from 'three';
import { Version } from '../types';

export const crystalClear: Version = {
    name: 'Crystal Clear',
    uniforms: {
        uArtisticBlend: 0,
        uDisplacementScale: 0.167,
        uVelocityShiftScale: 0.0105,
        uDensityShiftScale: 0.0481,
        uWaterColor: "#7ea3e7",
        uInkColor: "#b3d4ff",
        uVolumeFactor: 0.67,
        uInkStrength: 0.25,
        uShininess: 1006,
        uFresnelColor: "#5a99b5",
        uFresnelIntensity: 4.5,
        uGlowColor: "#7a94e1",
        uGlowPower: 6,
        uInkGeneration: 0.05,
        uWaveSize: 0.142,
        uWaveSteepness: 0.104,
        uWaveComplexity: 0.037,
        uWaveDetail: 0.033,
        uFeedRate: 0.021,
        uKillRate: 0.029,
        uVorticity: 1,
        uReactionForce: 0.14,
        uBuoyancy: 0.22,
        uAmbientTemperature: 0,
        uSplatTemperature: 0,
        uBorderThickness: 0.03,
        uBorderColor: "#7ab6ff",
        uSurfaceTension: 0.06,
        uChiselStrength: 4.23,
        uSSR_Strength: 0.26,
        uSSR_Falloff: 1,
        uSSR_Samples: 8,
        uParticleRate: 0,
        uParticleSize: 0,
        uParticleAdvection: 0,
        uParticleColor: "#ffffff",
        uCausticsIntensity: 1.7,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0.07,
        uFlowSpeed: 0,
        uRippleStrength: 0,
        uRippleDamping: 0.9,
        uRippleSpeed: 0,
        uLight1Pos: new THREE.Vector3(0.5, 0.5, 0.6),
        uLight1Color: "#eef2ff",
        uLight2Pos: new THREE.Vector3(-0.5, -0.5, 0.4),
        uLight2Color: "#b1b1c3",
    },
    simParams: {
        waveDecay: 0.923,
        densityDissipation: 0.907,
        temperatureDissipation: 0.937
    }
};
