import * as THREE from 'three';
import { Version } from '../types';

export const crystalClear: Version = {
    name: 'Crystal Clear',
    uniforms: {
        uArtisticBlend: 0.0,
        uDisplacementScale: 0.058,
        uVelocityShiftScale: 0.001,
        uDensityShiftScale: 0.0059,
        uWaterColor: new THREE.Color(0.6, 0.8, 0.9),
        uInkColor: new THREE.Color(0.8, 0.9, 1.0),
        uVolumeFactor: 0.81,
        uInkStrength: 0.55,
        uShininess: 92.0,
        uFresnelColor: new THREE.Color(1.0, 1.0, 1.0),
        uFresnelIntensity: 1.1,
        uGlowColor: new THREE.Color(0.8, 0.9, 1.0),
        uGlowPower: 0.8,
        uInkGeneration: 0.02,
        uWaveSize: 0.12,
        uWaveSteepness: 0.08,
        uWaveComplexity: 0.028,
        uWaveDetail: 0.033,
        uFeedRate: 0.017,
        uKillRate: 0.036,
        uVorticity: 0.0,
        uReactionForce: 0.14,
        uBuoyancy: 0.22,
        uAmbientTemperature: 0.0,
        uSplatTemperature: 0.0,
        uBorderThickness: 0.05,
        uBorderColor: new THREE.Color(0.1, 0.1, 0.1),
        uSurfaceTension: 0.06,
        uChiselStrength: 3.0,
        uSSR_Strength: 0.0,
        uSSR_Falloff: 2.8,
        uSSR_Samples: 0,
        uParticleRate: 0.0,
        uParticleSize: 2.0,
        uParticleAdvection: 0.2,
        uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
        uCausticsIntensity: 0.1,
        uLightDepth: 0.6,
        uSurfaceDetailStrength: 0.04,
        uFlowSpeed: 0.9,
        uRippleStrength: 1.0,
        uRippleDamping: 0.98,
        uRippleSpeed: 0.5,
        uLight1Pos: new THREE.Vector3(0.5, 0.5, 0.6),
        uLight1Color: new THREE.Color(0.8, 0.9, 1.0),
        uLight2Pos: new THREE.Vector3(-0.5, -0.5, 0.4),
        uLight2Color: new THREE.Color(0.5, 0.8, 1.0),
    },
    simParams: { waveDecay: 0.856, densityDissipation: 0.927, temperatureDissipation: 0.88 }
};