import * as THREE from 'three';
import { Version } from '../types';

export const deepOcean: Version = {
    name: 'Deep Ocean',
    uniforms: {
        uArtisticBlend: 0.0,
        uDisplacementScale: 0.07,
        uVelocityShiftScale: 0.002,
        uDensityShiftScale: 0.002,
        uWaterColor: new THREE.Color(0.01, 0.04, 0.15),
        uInkColor: new THREE.Color(0.5, 0.8, 1.0),
        uVolumeFactor: 1.0,
        uInkStrength: 4.0,
        uShininess: 30.0,
        uFresnelColor: new THREE.Color(0.2, 0.8, 1.0), uFresnelIntensity: 1.2,
        uGlowColor: new THREE.Color(0.1, 0.4, 0.6), uGlowPower: 2.5,
        uInkGeneration: 0.01,
        uWaveSize: 0.16,
        uWaveSteepness: 0.05,
        uWaveComplexity: 0.05,
        uWaveDetail: 0.0,
        uFeedRate: 0.0,
        uKillRate: 0.0,
        uVorticity: 0.0,
        uReactionForce: 0.0,
        uBuoyancy: 0.0,
        uAmbientTemperature: 0.0,
        uSplatTemperature: 0.0,
        uBorderThickness: 0.0,
        uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
        uSurfaceTension: 0.1,
        uChiselStrength: 0.8,
        uSSR_Strength: 0.0,
        uSSR_Falloff: 1.0,
        uSSR_Samples: 0,
        uParticleRate: 0.0,
        uParticleSize: 2.0,
        uParticleAdvection: 0.2,
        uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
        uCausticsIntensity: 1.5,
        uLightDepth: 0.9,
        uSurfaceDetailStrength: 0.15,
        uFlowSpeed: 2.0,
        uRippleStrength: 0.9,
        uRippleDamping: 0.988,
        uRippleSpeed: 0.3,
        uLight1Pos: new THREE.Vector3(0.5, 1.0, 0.9),
        uLight1Color: new THREE.Color(0.5, 0.8, 1.0),
        uLight2Pos: new THREE.Vector3(0.5, 0.0, 0.1),
        uLight2Color: new THREE.Color(0.1, 0.4, 0.6),
    },
    simParams: { waveDecay: 0.995, densityDissipation: 0.99, temperatureDissipation: 0.98 }
};
