import * as THREE from 'three';
import { Version } from '../types';

export const etherealGlow: Version = {
    name: 'Ethereal Glow',
    uniforms: {
        uArtisticBlend: 1.0,
        uDisplacementScale: 0.12,
        uVelocityShiftScale: 0.004,
        uDensityShiftScale: 0.006,
        uWaterColor: new THREE.Color(0.1, 0.2, 0.25),
        uInkColor: new THREE.Color(0.8, 1.0, 0.9),
        uVolumeFactor: 0.3,
        uInkStrength: 0.8,
        uShininess: 30.0,
        uFresnelColor: new THREE.Color(1.0, 0.6, 0.8), uFresnelIntensity: 2.5,
        uGlowColor: new THREE.Color(0.5, 1.0, 0.8), uGlowPower: 2.0,
        uInkGeneration: 0.2,
        uWaveSize: 0.14,
        uWaveSteepness: 0.09,
        uWaveComplexity: 0.0,
        uWaveDetail: 0.0,
        uFeedRate: 0.0,
        uKillRate: 0.0,
        uVorticity: 0.0,
        uReactionForce: 0.0,
        uBuoyancy: 0.0,
        uAmbientTemperature: 0.0,
        uSplatTemperature: 0.0,
        uBorderThickness: 0.0,
        uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
        uSurfaceTension: 0.05,
        uChiselStrength: 0.5,
        uSSR_Strength: 0.0,
        uSSR_Falloff: 1.0,
        uSSR_Samples: 0,
        uParticleRate: 0.0,
        uParticleSize: 2.0,
        uParticleAdvection: 0.2,
        uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
        uCausticsIntensity: 0.0,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0.0,
        uFlowSpeed: 1.0,
        uRippleStrength: 0.6,
        uRippleDamping: 0.985,
        uRippleSpeed: 0.4,
        uLight1Pos: new THREE.Vector3(0.2, 0.8, 0.5),
        uLight1Color: new THREE.Color(0.5, 1.0, 0.8),
        uLight2Pos: new THREE.Vector3(0.8, 0.2, 0.5),
        uLight2Color: new THREE.Color(1.0, 0.6, 0.8),
    },
    simParams: { waveDecay: 0.993, densityDissipation: 0.996, temperatureDissipation: 0.98 }
};
