import * as THREE from 'three';
import { Version } from '../types';

export const liquidChrome: Version = {
    name: 'Liquid Chrome',
    uniforms: {
        uArtisticBlend: 0.15,
        uDisplacementScale: 0.15,
        uVelocityShiftScale: 0.001,
        uDensityShiftScale: 0.002,
        uWaterColor: new THREE.Color(0.05, 0.05, 0.08),
        uInkColor: new THREE.Color(1.0, 1.0, 1.0),
        uVolumeFactor: 0.6,
        uInkStrength: 3.0,
        uShininess: 250.0,
        uFresnelColor: new THREE.Color(0.9, 0.95, 1.0),
        uFresnelIntensity: 3.5,
        uGlowColor: new THREE.Color(0.4, 0.6, 1.0),
        uGlowPower: 3.0,
        uInkGeneration: 0.1,
        uWaveSize: 0.1,
        uWaveSteepness: 0.12,
        uWaveComplexity: 0.01,
        uWaveDetail: 0.005,
        uFeedRate: 0.0,
        uKillRate: 0.0,
        uVorticity: 8.0,
        uReactionForce: 0.0,
        uBuoyancy: 0.0,
        uAmbientTemperature: 0.0,
        uSplatTemperature: 0.0,
        uBorderThickness: 0.0,
        uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
        uSurfaceTension: 1.2,
        uChiselStrength: 2.5,
        uSSR_Strength: 2.0,
        uSSR_Falloff: 1.5,
        uSSR_Samples: 20,
        uParticleRate: 0.0,
        uParticleSize: 2.0,
        uParticleAdvection: 0.2,
        uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
        uCausticsIntensity: 0.0,
        uLightDepth: 0.2,
        uSurfaceDetailStrength: 0.6,
        uFlowSpeed: 1.0,
        uRippleStrength: 0.6,
        uRippleDamping: 0.97,
        uRippleSpeed: 0.6,
        uLight1Pos: new THREE.Vector3(0.2, 0.8, 0.7),
        uLight1Color: new THREE.Color(0.4, 0.6, 1.0),
        uLight2Pos: new THREE.Vector3(0.8, 0.2, 0.3),
        uLight2Color: new THREE.Color(1.0, 1.0, 1.0),
    },
    simParams: { waveDecay: 0.98, densityDissipation: 0.99, temperatureDissipation: 0.98 }
};
