import * as THREE from 'three';
import { Version } from '../types';

export const livingInk: Version = {
    name: 'Living Ink',
    uniforms: {
        uArtisticBlend: 0.2,
        uDisplacementScale: 0.06,
        uVelocityShiftScale: 0.005,
        uDensityShiftScale: 0.01,
        uWaterColor: new THREE.Color(0.0, 0.01, 0.02),
        uInkColor: new THREE.Color(0.0, 1.0, 0.7),
        uVolumeFactor: 0.5,
        uInkStrength: 2.5,
        uShininess: 150.0,
        uFresnelColor: new THREE.Color(0.2, 1.0, 0.7),
        uFresnelIntensity: 2.0,
        uGlowColor: new THREE.Color(0.0, 0.7, 1.0),
        uGlowPower: 3.0,
        uInkGeneration: 0.0,
        uWaveSize: 0.1,
        uWaveSteepness: 0.05,
        uWaveComplexity: 0.1,
        uWaveDetail: 0.005,
        uFeedRate: 0.037,
        uKillRate: 0.06,
        uVorticity: 20.0,
        uReactionForce: 0.8,
        uBuoyancy: 0.05,
        uAmbientTemperature: 0.0,
        uSplatTemperature: 0.01,
        uBorderThickness: 0.0,
        uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
        uSurfaceTension: 0.5,
        uChiselStrength: 1.2,
        uSSR_Strength: 0.8,
        uSSR_Falloff: 2.5,
        uSSR_Samples: 8,
        uParticleRate: 0.0,
        uParticleSize: 2.0,
        uParticleAdvection: 0.2,
        uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
        uCausticsIntensity: 0.0,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0.1,
        uFlowSpeed: 5.0,
        uRippleStrength: 0.5,
        uRippleDamping: 0.97,
        uRippleSpeed: 0.4,
        uLight1Pos: new THREE.Vector3(0.5, 1.0, 0.6),
        uLight1Color: new THREE.Color(0.0, 1.0, 0.7),
        uLight2Pos: new THREE.Vector3(0.5, 0.0, 0.4),
        uLight2Color: new THREE.Color(1.0, 1.0, 1.0),
    },
    simParams: { waveDecay: 0.992, densityDissipation: 0.996, temperatureDissipation: 0.99 }
};
