import * as THREE from 'three';
import { Version } from '../types';

export const luminousGel: Version = {
    name: 'Luminous Gel',
    uniforms: {
        uArtisticBlend: 1,
        uDisplacementScale: 0.04,
        uVelocityShiftScale: 0.003,
        uDensityShiftScale: 0.005,
        uWaterColor: new THREE.Color("#33194c"),
        uInkColor: new THREE.Color("#ccb2ff"),
        uVolumeFactor: 0.9,
        uInkStrength: 1.8,
        uShininess: 150,
        uFresnelColor: new THREE.Color("#373120"),
        uFresnelIntensity: 1.5,
        uGlowColor: new THREE.Color("#99ccff"),
        uGlowPower: 2.2,
        uInkGeneration: 0.1,
        uWaveSize: 0.117,
        uWaveSteepness: 0.01,
        uWaveComplexity: 0,
        uWaveDetail: 0,
        uFeedRate: 0.011,
        uKillRate: 0.02,
        uVorticity: 0,
        uReactionForce: 0,
        uBuoyancy: 0,
        uAmbientTemperature: 0.03,
        uSplatTemperature: -0.22,
        uBorderThickness: 0,
        uBorderColor: new THREE.Color("#000000"),
        uSurfaceTension: 1,
        uChiselStrength: 3.5,
        uSSR_Strength: 0.57,
        uSSR_Falloff: 0.2,
        uSSR_Samples: 0,
        uParticleRate: 0.46,
        uParticleSize: 2,
        uParticleAdvection: 0.2,
        uParticleColor: new THREE.Color("#ffffff"),
        uCausticsIntensity: 0.1,
        uLightDepth: 0.3,
        uSurfaceDetailStrength: 0,
        uFlowSpeed: 1,
        uRippleStrength: 0,
        uRippleDamping: 0.9,
        uRippleSpeed: 0,
        uLight1Pos: new THREE.Vector3(0.7, 0.7, 0.4),
        uLight1Color: new THREE.Color("#090118"),
        uLight2Pos: new THREE.Vector3(0.3, 0.3, 0.6),
        uLight2Color: new THREE.Color("#99ccff")
    },
    simParams: {
        waveDecay: 1,
        densityDissipation: 0.98,
        temperatureDissipation: 0.98
    }
};