import * as THREE from 'three';
import { Version } from '../types';

export const luminousGel: Version = {
    name: 'Luminous Gel',
    uniforms: {
        uArtisticBlend: 1.0,
        uDisplacementScale: 0.05,
        uVelocityShiftScale: 0.006,
        uDensityShiftScale: 0.03,
        uWaterColor: new THREE.Color(0.4, 0.0, 0.15),
        uInkColor: new THREE.Color(1.0, 0.8, 0.9),
        uVolumeFactor: 0.8,
        uInkStrength: 2.0,
        uShininess: 120.0,
        uFresnelColor: new THREE.Color(1.0, 0.9, 0.2),
        uFresnelIntensity: 2.5,
        uGlowColor: new THREE.Color(1.0, 0.1, 0.3),
        uGlowPower: 2.0,
        uInkGeneration: 0.1,
        uWaveSize: 0.08,
        uWaveSteepness: 0.04,
        uWaveComplexity: 0.0,
        uWaveDetail: 0.0,
        uFeedRate: 0.0,
        uKillRate: 0.0,
        uVorticity: 0.0,
        uReactionForce: 0.0,
        uBuoyancy: 0.0,
        uAmbientTemperature: 0.0,
        uSplatTemperature: 0.0,
        uBorderThickness: 0.0,
        uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
        uSurfaceTension: 0.8,
        uChiselStrength: 2.0,
        uSSR_Strength: 0.0,
        uSSR_Falloff: 1.0,
        uSSR_Samples: 0,
        uParticleRate: 0.0,
        uParticleSize: 2.0,
        uParticleAdvection: 0.2,
        uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
        uCausticsIntensity: 0.1,
        uLightDepth: 0.3,
        uSurfaceDetailStrength: 0.05,
        uFlowSpeed: 1.0,
        uRippleStrength: 0.2,
        uRippleDamping: 0.95,
        uRippleSpeed: 0.1,
        uLight1Pos: new THREE.Vector3(0.7, 0.7, 0.4),
        uLight1Color: new THREE.Color(1.0, 0.1, 0.3),
        uLight2Pos: new THREE.Vector3(0.3, 0.3, 0.6),
        uLight2Color: new THREE.Color(1.0, 0.9, 0.2),
    },
    simParams: { waveDecay: 0.98, densityDissipation: 0.98, temperatureDissipation: 0.98 }
};
