import * as THREE from 'three';
import { Version } from '../types';

export const luminousGel: Version = {
    name: 'Luminous Gel',
    uniforms: {
        uArtisticBlend: 1,
        uDisplacementScale: 0.04,
        uVelocityShiftScale: 0.0078,
        uDensityShiftScale: 0.005,
        uWaterColor: "#4d4d4d",
        uInkColor: "#1b3b64",
        uVolumeFactor: 0.79,
        uInkStrength: 1.4,
        uShininess: 271,
        uFresnelColor: "#000000",
        uFresnelIntensity: 2.2,
        uGlowColor: "#f2f2f2",
        uGlowPower: 8.3,
        uInkGeneration: 0.05,
        uWaveSize: 0.117,
        uWaveSteepness: 0.063,
        uWaveComplexity: 0,
        uWaveDetail: 0,
        uFeedRate: 0.026,
        uKillRate: 0.021,
        uVorticity: 0,
        uReactionForce: 1.02,
        uBuoyancy: 0,
        uAmbientTemperature: 0.03,
        uSplatTemperature: 0.23,
        uBorderThickness: 0,
        uBorderColor: "#fffafa",
        uSurfaceTension: 1,
        uChiselStrength: 3.5,
        uSSR_Strength: 0.51,
        uSSR_Falloff: 0.2,
        uSSR_Samples: 0,
        uParticleRate: 0,
        uParticleSize: 2,
        uParticleAdvection: 0.2,
        uParticleColor: "#ffffff",
        uCausticsIntensity: 0,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0,
        uFlowSpeed: 1,
        uRippleStrength: 0.01,
        uRippleDamping: 0.94,
        uRippleSpeed: 0.82,
        uLight1Pos: new THREE.Vector3(0.7, 0.7, 0.4),
        uLight1Color: "#eef2ff",
        uLight2Pos: new THREE.Vector3(0.3, 0.3, 0.6),
        uLight2Color: "#b1b1c3"
    },
    simParams: {
        waveDecay: 0.945,
        densityDissipation: 0.888,
        temperatureDissipation: 0.948
    }
};
