import * as THREE from 'three';
import { Version } from '../types';

export const lusion: Version = {
    name: 'Lusion',
    uniforms: {
        uArtisticBlend: 0.1,
        uDisplacementScale: 0.09,
        uVelocityShiftScale: 0.002,
        uDensityShiftScale: 0.006,
        uWaterColor: new THREE.Color(0.01, 0.0, 0.02),
        uInkColor: new THREE.Color(0.3, 0.8, 1.0),
        uVolumeFactor: 0.85,
        uInkStrength: 4.5,
        uShininess: 280.0,
        uFresnelColor: new THREE.Color(0.1, 0.7, 1.0), uFresnelIntensity: 3.0,
        uGlowColor: new THREE.Color(0.2, 0.5, 1.0), uGlowPower: 2.0,
        uInkGeneration: 0.08,
        uWaveSize: 0.09,
        uWaveSteepness: 0.06,
        uWaveComplexity: 0.02,
        uWaveDetail: 0.01,
        uFeedRate: 0.0,
        uKillRate: 0.0,
        uVorticity: 10.0,
        uReactionForce: 0.0,
        uBuoyancy: 0.0,
        uAmbientTemperature: 0.0,
        uSplatTemperature: 0.0,
        uBorderThickness: 0.0,
        uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
        uSurfaceTension: 0.4,
        uChiselStrength: 1.8,
        uSSR_Strength: 0.0,
        uSSR_Falloff: 1.0,
        uSSR_Samples: 0,
        uParticleRate: 0.0,
        uParticleSize: 2.0,
        uParticleAdvection: 0.2,
        uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
        uCausticsIntensity: 0.2,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0.1,
        uFlowSpeed: 2.0,
        uRippleStrength: 0.8,
        uRippleDamping: 0.975,
        uRippleSpeed: 0.5,
        uLight1Pos: new THREE.Vector3(0.1, 0.8, 0.5),
        uLight1Color: new THREE.Color(0.1, 0.7, 1.0),
        uLight2Pos: new THREE.Vector3(0.9, 0.2, 0.5),
        uLight2Color: new THREE.Color(0.2, 0.5, 1.0),
    },
    simParams: { waveDecay: 0.988, densityDissipation: 0.98, temperatureDissipation: 0.98 }
};
