import * as THREE from 'three';
import { Version } from '../types';

export const mercury: Version = {
    name: 'Mercury',
    uniforms: {
        uArtisticBlend: 0.0,
        uDisplacementScale: 0.17,
        uVelocityShiftScale: 0.0005,
        uDensityShiftScale: 0.0171,
        uWaterColor: new THREE.Color(0.15, 0.18, 0.2),
        uInkColor: new THREE.Color(1.0, 1.0, 1.0),
        uVolumeFactor: 0.55,
        uInkStrength: 1.2,
        uShininess: 190.0,
        uFresnelColor: new THREE.Color(0.9, 0.95, 1.0),
        uFresnelIntensity: 2.0,
        uGlowColor: new THREE.Color(0.8, 0.9, 1.0),
        uGlowPower: 1.0,
        uInkGeneration: 0.0,
        uWaveSize: 0.08,
        uWaveSteepness: 0.15,
        uWaveComplexity: 0.116,
        uWaveDetail: 0.031,
        uFeedRate: 0.026,
        uKillRate: 0.053,
        uVorticity: 2.7,
        uReactionForce: 0.91,
        uBuoyancy: 0.77,
        uAmbientTemperature: 0.24,
        uSplatTemperature: 0.0,
        uBorderThickness: 0.0,
        uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
        uSurfaceTension: 0.61,
        uChiselStrength: 3.0,
        uSSR_Strength: 0.17,
        uSSR_Falloff: 1.5,
        uSSR_Samples: 25,
        uParticleRate: 0.0,
        uParticleSize: 2.0,
        uParticleAdvection: 0.2,
        uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
        uCausticsIntensity: 0.0,
        uLightDepth: 0.1,
        uSurfaceDetailStrength: 0.01,
        uFlowSpeed: 5.5,
        uRippleStrength: 0.4,
        uRippleDamping: 0.97,
        uRippleSpeed: 0.2,
        uLight1Pos: new THREE.Vector3(1.0, 1.0, 0.8),
        uLight1Color: new THREE.Color(0.9, 0.9, 0.9),
        uLight2Pos: new THREE.Vector3(-0.5, -0.5, 0.5),
        uLight2Color: new THREE.Color(0.5, 0.5, 0.5),
    },
    simParams: { waveDecay: 0.968, densityDissipation: 0.973, temperatureDissipation: 0.98 }
};