import * as THREE from 'three';
import { Version } from '../types';

export const mercury: Version = {
    name: 'Mercury',
    uniforms: {
        uArtisticBlend: 0,
        uDisplacementScale: 0.17,
        uVelocityShiftScale: 0,
        uDensityShiftScale: 0.0171,
        uWaterColor: "#4d4d4d",
        uInkColor: "#1b3b64",
        uVolumeFactor: 0.55,
        uInkStrength: 0.8,
        uShininess: 992,
        uFresnelColor: "#000000",
        uFresnelIntensity: 1.6,
        uGlowColor: "#f2f2f2",
        uGlowPower: 4.8,
        uInkGeneration: 0.05,
        uWaveSize: 0.08,
        uWaveSteepness: 0.143,
        uWaveComplexity: 0.132,
        uWaveDetail: 0.031,
        uFeedRate: 0.01,
        uKillRate: 0.037,
        uVorticity: 0.3,
        uReactionForce: 0,
        uBuoyancy: 1.45,
        uAmbientTemperature: 0.24,
        uSplatTemperature: -1,
        uBorderThickness: 0,
        uBorderColor: "#fffafa",
        uSurfaceTension: 1.88,
        uChiselStrength: 1.52,
        uSSR_Strength: 0,
        uSSR_Falloff: 1.5,
        uSSR_Samples: 25,
        uParticleRate: 0,
        uParticleSize: 2,
        uParticleAdvection: 0.2,
        uParticleColor: "#ffffff",
        uCausticsIntensity: 0,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0.01,
        uFlowSpeed: 5.5,
        uRippleStrength: 0,
        uRippleDamping: 0.97,
        uRippleSpeed: 0.2,
        uLight1Pos: new THREE.Vector3(1, 1, 0.8),
        uLight1Color: "#eef2ff",
        uLight2Pos: new THREE.Vector3(-0.5, -0.5, 0.5),
        uLight2Color: "#b1b1c3",
    },
    simParams: {
        waveDecay: 0.968,
        densityDissipation: 0.934,
        temperatureDissipation: 0.98
    }
};
