import * as THREE from 'three';
import { Version } from '../types';

export const moltenMetal: Version = {
    name: 'Molten Metal',
    uniforms: {
        uArtisticBlend: 0.9,
        uDisplacementScale: 0.04,
        uVelocityShiftScale: 0.00025,
        uDensityShiftScale: 0.00025,
        uWaterColor: new THREE.Color(0.1, 0.1, 0.12),
        uInkColor: new THREE.Color(1.0, 0.5, 0.1),
        uVolumeFactor: 0.9,
        uInkStrength: 5.0,
        uShininess: 300.0,
        uFresnelColor: new THREE.Color(0.95, 0.95, 1.0), uFresnelIntensity: 3.0,
        uGlowColor: new THREE.Color(1.0, 0.3, 0.0), uGlowPower: 3.5,
        uInkGeneration: 0.005,
        uWaveSize: 0.06,
        uWaveSteepness: 0.03,
        uWaveComplexity: 0.01,
        uWaveDetail: 0.002,
        uFeedRate: 0.0,
        uKillRate: 0.0,
        uVorticity: 0.0,
        uReactionForce: 0.0,
        uBuoyancy: 0.0,
        uAmbientTemperature: 0.0,
        uSplatTemperature: 0.0,
        uBorderThickness: 0.0,
        uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
        uSurfaceTension: 1.0,
        uChiselStrength: 2.5,
        uSSR_Strength: 1.5,
        uSSR_Falloff: 2.0,
        uSSR_Samples: 15,
        uParticleRate: 0.0,
        uParticleSize: 2.0,
        uParticleAdvection: 0.2,
        uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
        uCausticsIntensity: 0.0,
        uLightDepth: 0.1,
        uSurfaceDetailStrength: 0.4,
        uFlowSpeed: 0.5,
        uRippleStrength: 0.3,
        uRippleDamping: 0.9,
        uRippleSpeed: 0.08,
        uLight1Pos: new THREE.Vector3(0.5, 0.5, 0.4),
        uLight1Color: new THREE.Color(1.0, 0.5, 0.1),
        uLight2Pos: new THREE.Vector3(0.5, 0.5, 0.6),
        uLight2Color: new THREE.Color(1.0, 0.3, 0.0),
    },
    simParams: { waveDecay: 0.95, densityDissipation: 0.97, temperatureDissipation: 0.98 }
};
