import * as THREE from 'three';
import { Version } from '../types';

export const neoWater: Version = {
    name: 'Neo Water',
    uniforms: {
        uArtisticBlend: 0,
        uDisplacementScale: 0.139,
        uVelocityShiftScale: 0.0035,
        uDensityShiftScale: 0.002,
        uWaterColor: "#564f7d",
        uInkColor: "#446ea2",
        uVolumeFactor: 0.71,
        uInkStrength: 1,
        uShininess: 701,
        uFresnelColor: "#ad64dd",
        uFresnelIntensity: 3.7,
        uGlowColor: "#e7b5ee",
        uGlowPower: 8.1,
        uInkGeneration: 0.05,
        uWaveSize: 0.117,
        uWaveSteepness: 0.129,
        uWaveComplexity: 0.054,
        uWaveDetail: 0,
        uFeedRate: 0.035,
        uKillRate: 0.047,
        uVorticity: 1.5,
        uReactionForce: 0.22,
        uBuoyancy: 0.63,
        uAmbientTemperature: 0.62,
        uSplatTemperature: 0.63,
        uBorderThickness: 0,
        uBorderColor: "#000000",
        uSurfaceTension: 0.11,
        uChiselStrength: 1.77,
        uSSR_Strength: 0,
        uSSR_Falloff: 0.9,
        uSSR_Samples: 7,
        uParticleRate: 0.78,
        uParticleSize: 4.7,
        uParticleAdvection: 0.2,
        uParticleColor: "#ffffff",
        uCausticsIntensity: 1.5,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0,
        uFlowSpeed: 5,
        uRippleStrength: 0,
        uRippleDamping: 0.985,
        uRippleSpeed: 0.6,
        uLight1Pos: new THREE.Vector3(0.9, 0.9, 0.5),
        uLight1Color: "#eef2ff",
        uLight2Pos: new THREE.Vector3(0.1, 0.1, 0.5),
        uLight2Color: "#b1b1c3",
    },
    simParams: {
        waveDecay: 0.992,
        densityDissipation: 0.931,
        temperatureDissipation: 0.98
    }
};