import * as THREE from 'three';
import { Version } from '../types';

export const neoWater: Version = {
    name: 'Neo Water',
    uniforms: {
        uArtisticBlend: 0.0,
        uDisplacementScale: 0.139,
        uVelocityShiftScale: 0.0045,
        uDensityShiftScale: 0.002,
        uWaterColor: new THREE.Color(0.7, 0.85, 0.95),
        uInkColor: new THREE.Color(0.8, 0.9, 1.0),
        uVolumeFactor: 0.34,
        uInkStrength: 1.0,
        uShininess: 599.0,
        uFresnelColor: new THREE.Color(1.0, 1.0, 1.0),
        uFresnelIntensity: 3.3,
        uGlowColor: new THREE.Color(0.8, 0.9, 1.0),
        uGlowPower: 7.3,
        uInkGeneration: 0.05,
        uWaveSize: 0.095,
        uWaveSteepness: 0.129,
        uWaveComplexity: 0.054,
        uWaveDetail: 0.008,
        uFeedRate: 0.029,
        uKillRate: 0.047,
        uVorticity: 0.1,
        uReactionForce: 0.22,
        uBuoyancy: 0.0,
        uAmbientTemperature: 0.13,
        uSplatTemperature: 0.0,
        uBorderThickness: 0.019,
        uBorderColor: new THREE.Color('#A8C8D6'),
        uSurfaceTension: 0.11,
        uChiselStrength: 4.56,
        uSSR_Strength: 0.12,
        uSSR_Falloff: 0.9,
        uSSR_Samples: 7,
        uParticleRate: 0.78,
        uParticleSize: 4.7,
        uParticleAdvection: 0.2,
        uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
        uCausticsIntensity: 4.1,
        uLightDepth: 0.7,
        uSurfaceDetailStrength: 0.0,
        uFlowSpeed: 5.0,
        uRippleStrength: 0.8,
        uRippleDamping: 0.985,
        uRippleSpeed: 0.6,
        uLight1Pos: new THREE.Vector3(0.9, 0.9, 0.5),
        uLight1Color: new THREE.Color(1.0, 1.0, 1.0),
        uLight2Pos: new THREE.Vector3(0.1, 0.1, 0.5),
        uLight2Color: new THREE.Color(0.2, 0.5, 1.0),
    },
    simParams: { waveDecay: 0.992, densityDissipation: 0.937, temperatureDissipation: 0.98 }
};
