import * as THREE from 'three';
import { Version } from '../types';

export const neoWater: Version = {
    name: 'Neo Water',
    uniforms: {
        uArtisticBlend: 0,
        uDisplacementScale: 0.139,
        uVelocityShiftScale: 0.0045,
        uDensityShiftScale: 0.002,
        uWaterColor: "#4d4d4d",
        uInkColor: "#1b3b64",
        uVolumeFactor: 0.34,
        uInkStrength: 1,
        uShininess: 701,
        uFresnelColor: "#000000",
        uFresnelIntensity: 2.5,
        uGlowColor: "#f2f2f2",
        uGlowPower: 8.1,
        uInkGeneration: 0.05,
        uWaveSize: 0.095,
        uWaveSteepness: 0.129,
        uWaveComplexity: 0.054,
        uWaveDetail: 0.008,
        uFeedRate: 0.029,
        uKillRate: 0.047,
        uVorticity: 0.1,
        uReactionForce: 0.22,
        uBuoyancy: 0,
        uAmbientTemperature: 0.13,
        uSplatTemperature: 0,
        uBorderThickness: 0.019,
        uBorderColor: "#fffafa",
        uSurfaceTension: 0.11,
        uChiselStrength: 4.56,
        uSSR_Strength: 0,
        uSSR_Falloff: 0.9,
        uSSR_Samples: 7,
        uParticleRate: 0.78,
        uParticleSize: 4.7,
        uParticleAdvection: 0.2,
        uParticleColor: "#ffffff",
        uCausticsIntensity: 1.5,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0,
        uFlowSpeed: 5,
        uRippleStrength: 0,
        uRippleDamping: 0.985,
        uRippleSpeed: 0.6,
        uLight1Pos: new THREE.Vector3(0.9, 0.9, 0.5),
        uLight1Color: "#eef2ff",
        uLight2Pos: new THREE.Vector3(0.1, 0.1, 0.5),
        uLight2Color: "#b1b1c3",
    },
    simParams: {
        waveDecay: 0.992,
        densityDissipation: 0.931,
        temperatureDissipation: 0.98
    }
};
