import * as THREE from 'three';
import { Version } from '../types';

export const pristineWater: Version = {
    name: 'Pristine Water',
    uniforms: {
        uArtisticBlend: 0.0,
        uDisplacementScale: 0.06,
        uVelocityShiftScale: 0.0003,
        uDensityShiftScale: 0.001,
        uWaterColor: "#4d4d4d",
        uInkColor: "#1b3b64",
        uVolumeFactor: 0.96,
        uInkStrength: 0.65,
        uShininess: 500.0,
        uFresnelColor: "#000000",
        uFresnelIntensity: 3.1,
        uGlowColor: "#f2f2f2",
        uGlowPower: 8.9,
        uInkGeneration: 0.05,
        uWaveSize: 0.126,
        uWaveSteepness: 0.1,
        uWaveComplexity: 0.002,
        uWaveDetail: 0.028,
        uFeedRate: 0.016,
        uKillRate: 0.024,
        uVorticity: 2.0,
        uReactionForce: 0.0,
        uBuoyancy: 0.72,
        uAmbientTemperature: 0.84,
        uSplatTemperature: -0.26,
        uBorderThickness: 0.051,
        uBorderColor: "#fffafa",
        uSurfaceTension: 0.18,
        uChiselStrength: 3.5,
        uSSR_Strength: 0.47,
        uSSR_Falloff: 1.2,
        uSSR_Samples: 6,
        uParticleRate: 1.22,
        uParticleSize: 1.0,
        uParticleAdvection: 0.5,
        uParticleColor: "#ffffff",
        uCausticsIntensity: 1.0,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0.03,
        uFlowSpeed: 3.0,
        uRippleStrength: 0.0,
        uRippleDamping: 0.98,
        uRippleSpeed: 0.6,
        uLight1Pos: new THREE.Vector3(1.0, 0.94, 0.65),
        uLight1Color: "#eef2ff",
        uLight2Pos: new THREE.Vector3(0.2, 0.2, 0.72),
        uLight2Color: "#b1b1c3",
    },
    simParams: { 
        waveDecay: 0.948, 
        densityDissipation: 0.893, 
        temperatureDissipation: 0.98 
    }
};
