
import * as THREE from 'three';
import { Version } from '../types';

export const pristineWater: Version = {
    name: 'Pristine Water',
    uniforms: {
        uArtisticBlend: 0.0,
        uDisplacementScale: 0.06,
        uVelocityShiftScale: 0.0003,
        uDensityShiftScale: 0.001,
        uWaterColor: new THREE.Color(0.8, 0.9, 1.0),
        uInkColor: new THREE.Color(0.8, 0.9, 1.0),
        uVolumeFactor: 0.96,
        uInkStrength: 0.65,
        uShininess: 773.0,
        uFresnelColor: new THREE.Color(1.0, 1.0, 1.0),
        uFresnelIntensity: 3.4,
        uGlowColor: new THREE.Color(0.8, 0.9, 1.0),
        uGlowPower: 10.0,
        uInkGeneration: 0.05,
        uWaveSize: 0.126,
        uWaveSteepness: 0.1,
        uWaveComplexity: 0.002,
        uWaveDetail: 0.028,
        uFeedRate: 0.0,
        uKillRate: 0.0,
        uVorticity: 2.0,
        uReactionForce: 0.0,
        uBuoyancy: 0.72,
        uAmbientTemperature: 0.12,
        uSplatTemperature: 0.0,
        uBorderThickness: 0.051,
        uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
        uSurfaceTension: 0.18,
        uChiselStrength: 3.5,
        uSSR_Strength: 0.07,
        uSSR_Falloff: 1.2,
        uSSR_Samples: 1,
        uParticleRate: 1.22,
        uParticleSize: 1.0,
        uParticleAdvection: 0.5,
        uParticleColor: new THREE.Color(0.8, 0.9, 1.0),
        uCausticsIntensity: 0.2,
        uLightDepth: 0.8,
        uSurfaceDetailStrength: 0.0,
        uFlowSpeed: 3.0,
        uRippleStrength: 1.2,
        uRippleDamping: 0.98,
        uRippleSpeed: 0.6,
        uLight1Pos: new THREE.Vector3(1.0, 0.94, 0.65),
        uLight1Color: new THREE.Color(1.0, 1.0, 1.0),
        uLight2Pos: new THREE.Vector3(0.2, 0.2, 0.72),
        uLight2Color: new THREE.Color(0.3, 0.6, 1.0),
    },
    simParams: { waveDecay: 0.993, densityDissipation: 0.934, temperatureDissipation: 0.98 }
};
