import * as THREE from 'three';
import { Version } from '../types';

export const pristineWater: Version = {
    name: 'Pristine Water',
    uniforms: {
        uArtisticBlend: 0,
        uDisplacementScale: 0.161,
        uVelocityShiftScale: 0.001,
        uDensityShiftScale: 0.0183,
        uWaterColor: "#61ced6",
        uInkColor: "#42ae93",
        uVolumeFactor: 0.75,
        uInkStrength: 0.45,
        uShininess: 964,
        uFresnelColor: "#635f5f",
        uFresnelIntensity: 3.8,
        uGlowColor: "#4eda99",
        uGlowPower: 8.3,
        uInkGeneration: 0.05,
        uWaveSize: 0.142,
        uWaveSteepness: 0.104,
        uWaveComplexity: 0.037,
        uWaveDetail: 0.033,
        uFeedRate: 0.021,
        uKillRate: 0.029,
        uVorticity: 1,
        uReactionForce: 0.14,
        uBuoyancy: 0.22,
        uAmbientTemperature: 0,
        uSplatTemperature: 0,
        uBorderThickness: 0.03,
        uBorderColor: "#55e2e0",
        uSurfaceTension: 0.06,
        uChiselStrength: 4.23,
        uSSR_Strength: 0,
        uSSR_Falloff: 2.8,
        uSSR_Samples: 5,
        uParticleRate: 0.2,
        uParticleSize: 1.5,
        uParticleAdvection: 0.2,
        uParticleColor: "#ffffff",
        uCausticsIntensity: 0,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0,
        uFlowSpeed: 0.26,
        uRippleStrength: 0,
        uRippleDamping: 0.98,
        uRippleSpeed: 0.5,
        uLight1Pos: new THREE.Vector3(0.5, 0.5, 0.6),
        uLight1Color: "#eef2ff",
        uLight2Pos: new THREE.Vector3(-0.5, -0.5, 0.4),
        uLight2Color: "#b1b1c3",
    },
    simParams: {
        waveDecay: 0.855,
        densityDissipation: 0.891,
        temperatureDissipation: 0.879
    }
};
