

import * as THREE from 'three';
import { Version } from '../types';

export const rainbowFlare: Version = {
    name: 'Rainbow Flare',
    uniforms: {
        uArtisticBlend: 0,
        uDisplacementScale: 0.093,
        uVelocityShiftScale: 0.0037,
        uDensityShiftScale: 0.0034,
        uWaterColor: new THREE.Color("#4d4d4d"),
        uInkColor: new THREE.Color("#1b3b64"),
        uVolumeFactor: 0.33,
        uInkStrength: 2.05,
        uShininess: 313,
        uFresnelColor: new THREE.Color("#000000"),
        uFresnelIntensity: 4.8,
        uGlowColor: new THREE.Color("#f2f2f2"),
        uGlowPower: 4.1,
        uInkGeneration: 0.05,
        uWaveSize: 0.098,
        uWaveSteepness: 0.15,
        uWaveComplexity: 0.146,
        uWaveDetail: 0.058,
        uFeedRate: 0.048,
        uKillRate: 0.041,
        uVorticity: 0,
        uReactionForce: 0.42,
        uBuoyancy: 1.77,
        uAmbientTemperature: 0.76,
        uSplatTemperature: -0.28,
        uBorderThickness: 0,
        uBorderColor: new THREE.Color("#fffafa"),
        uSurfaceTension: 0.39,
        uChiselStrength: 2.34,
        uSSR_Strength: 0.01,
        uSSR_Falloff: 1,
        uSSR_Samples: 15,
        uParticleRate: 0,
        uParticleSize: 4.4,
        uParticleAdvection: 0,
        uParticleColor: new THREE.Color("#ffffff"),
        uCausticsIntensity: 2.1,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0.03,
        uFlowSpeed: 0,
        uRippleStrength: 0.66,
        uRippleDamping: 0.943,
        uRippleSpeed: 0.94,
        uLight1Pos: new THREE.Vector3(-0.78, 0.5, 0.5),
        uLight1Color: new THREE.Color("#eef2ff"),
        uLight2Pos: new THREE.Vector3(0.77, 0.72, 0.65),
        uLight2Color: new THREE.Color("#b1b1c3"),
    },
    simParams: {
        waveDecay: 0.818,
        densityDissipation: 0.918,
        temperatureDissipation: 0.958,
    }
};