import * as THREE from 'three';
import { Version } from '../types';

export const rainbowFlare: Version = {
    name: 'Rainbow Flare',
    uniforms: {
        uArtisticBlend: 0.8,
        uDisplacementScale: 0.08,
        uVelocityShiftScale: 0.004,
        uDensityShiftScale: 0.01,
        uWaterColor: new THREE.Color(0.05, 0.0, 0.1),
        uInkColor: new THREE.Color(1.0, 1.0, 1.0),
        uVolumeFactor: 0.3,
        uInkStrength: 1.8,
        uShininess: 80.0,
        uFresnelColor: new THREE.Color(1.0, 0.7, 1.0),
        uFresnelIntensity: 3.0,
        uGlowColor: new THREE.Color(0.8, 0.9, 1.0),
        uGlowPower: 2.5,
        uInkGeneration: 0.05,
        uWaveSize: 0.1,
        uWaveSteepness: 0.06,
        uWaveComplexity: 0.01,
        uWaveDetail: 0.0,
        uFeedRate: 0.0,
        uKillRate: 0.0,
        uVorticity: 5.0,
        uReactionForce: 0.0,
        uBuoyancy: 0.0,
        uAmbientTemperature: 0.0,
        uSplatTemperature: 0.0,
        uBorderThickness: 0.0,
        uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
        uSurfaceTension: 0.2,
        uChiselStrength: 1.5,
        uSSR_Strength: 0.2,
        uSSR_Falloff: 2.0,
        uSSR_Samples: 5,
        uParticleRate: 0.1,
        uParticleSize: 3.0,
        uParticleAdvection: 0.3,
        uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
        uCausticsIntensity: 0.2,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0.05,
        uFlowSpeed: 2.0,
        uRippleStrength: 0.8,
        uRippleDamping: 0.985,
        uRippleSpeed: 0.5,
        uLight1Pos: new THREE.Vector3(0.0, 0.5, 0.5),
        uLight1Color: new THREE.Color(1.0, 0.2, 0.2),
        uLight2Pos: new THREE.Vector3(1.0, 0.5, 0.5),
        uLight2Color: new THREE.Color(0.2, 0.2, 1.0),
    },
    simParams: { waveDecay: 0.99, densityDissipation: 0.99, temperatureDissipation: 0.98 }
};
