
import * as THREE from 'three';
import { Version } from '../types';

export const rainbowFlare: Version = {
    name: 'Rainbow Flare',
    uniforms: {
        uArtisticBlend: 0,
        uDisplacementScale: 0.074,
        uVelocityShiftScale: 0.004,
        uDensityShiftScale: 0,
        uWaterColor: new THREE.Color("#4d4d4d"),
        uInkColor: new THREE.Color("#1b3b64"),
        uVolumeFactor: 0.84,
        uInkStrength: 0.6,
        uShininess: 308,
        uFresnelColor: new THREE.Color("#000000"),
        uFresnelIntensity: 1.7,
        uGlowColor: new THREE.Color("#f2f2f2"),
        uGlowPower: 1.2,
        uInkGeneration: 0.05,
        uWaveSize: 0.094,
        uWaveSteepness: 0.1,
        uWaveComplexity: 0.071,
        uWaveDetail: 0,
        uFeedRate: 0.017,
        uKillRate: 0,
        uVorticity: 0,
        uReactionForce: 1.46,
        uBuoyancy: 0.24,
        uAmbientTemperature: 0.99,
        uSplatTemperature: -1,
        uBorderThickness: 0,
        uBorderColor: new THREE.Color("#fffafa"),
        uSurfaceTension: 0.1,
        uChiselStrength: 1.28,
        uSSR_Strength: 0.43,
        uSSR_Falloff: 0.8,
        uSSR_Samples: 4,
        uParticleRate: 0.56,
        uParticleSize: 1,
        uParticleAdvection: 0,
        uParticleColor: new THREE.Color("#ffffff"),
        uCausticsIntensity: 0.6,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0,
        uFlowSpeed: 0,
        uRippleStrength: 0.22,
        uRippleDamping: 0.906,
        uRippleSpeed: 0.1,
        uLight1Pos: new THREE.Vector3(-0.78, 0.5, 0.5),
        uLight1Color: new THREE.Color("#eef2ff"),
        uLight2Pos: new THREE.Vector3(-0.53, 0.5, 0.65),
        uLight2Color: new THREE.Color("#b1b1c3"),
    },
    simParams: {
        waveDecay: 0.977,
        densityDissipation: 0.939,
        temperatureDissipation: 0.858,
    }
};