import * as THREE from 'three';
import { Version } from '../types';

export const sora: Version = {
    name: 'Sora',
    uniforms: {
        uArtisticBlend: 0,
        uDisplacementScale: 0.055,
        uVelocityShiftScale: 0.0006,
        uDensityShiftScale: 0.0042,
        uWaterColor: "#820792",
        uInkColor: "#641b5e",
        uVolumeFactor: 0.67,
        uInkStrength: 0.85,
        uShininess: 437,
        uFresnelColor: "#b706db",
        uFresnelIntensity: 3.2,
        uGlowColor: "#f42aaa",
        uGlowPower: 1.3,
        uInkGeneration: 0.05,
        uWaveSize: 0.157,
        uWaveSteepness: 0.119,
        uWaveComplexity: 0.014,
        uWaveDetail: 0.008,
        uFeedRate: 0.023,
        uKillRate: 0.028,
        uVorticity: 0.4,
        uReactionForce: 0.3,
        uBuoyancy: 2,
        uAmbientTemperature: 0.28,
        uSplatTemperature: 0,
        uBorderThickness: 0,
        uBorderColor: "#fffafa",
        uSurfaceTension: 0.84,
        uChiselStrength: 3.89,
        uSSR_Strength: 0.03,
        uSSR_Falloff: 4.3,
        uSSR_Samples: 2,
        uParticleRate: 0,
        uParticleSize: 2,
        uParticleAdvection: 0.2,
        uParticleColor: "#ffffff",
        uCausticsIntensity: 1.2,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0,
        uFlowSpeed: 0,
        uRippleStrength: 0,
        uRippleDamping: 0.98,
        uRippleSpeed: 0.7,
        uLight1Pos: new THREE.Vector3(0.8, 0.2, 0.7),
        uLight1Color: "#eef2ff",
        uLight2Pos: new THREE.Vector3(0.2, 0.8, 0.3),
        uLight2Color: "#b1b1c3",
    },
    simParams: {
        waveDecay: 0.976,
        densityDissipation: 0.88,
        temperatureDissipation: 0.885
    }
};
