import * as THREE from 'three';
import { Version } from '../types';

export const sora: Version = {
    name: 'Sora',
    uniforms: {
        uArtisticBlend: 0.0,
        uDisplacementScale: 0.055,
        uVelocityShiftScale: 0.0006,
        uDensityShiftScale: 0.0042,
        uWaterColor: new THREE.Color(0.02, 0.0, 0.05),
        uInkColor: new THREE.Color(0.7, 0.4, 1.0),
        uVolumeFactor: 0.67,
        uInkStrength: 1.5,
        uShininess: 615.0,
        uFresnelColor: new THREE.Color(1.0, 0.6, 0.8),
        uFresnelIntensity: 3.5,
        uGlowColor: new THREE.Color(0.8, 0.4, 1.0),
        uGlowPower: 0.6,
        uInkGeneration: 0.05,
        uWaveSize: 0.157,
        uWaveSteepness: 0.119,
        uWaveComplexity: 0.014,
        uWaveDetail: 0.008,
        uFeedRate: 0.023,
        uKillRate: 0.028,
        uVorticity: 0.4,
        uReactionForce: 0.3,
        uBuoyancy: 2.0,
        uAmbientTemperature: 0.28,
        uSplatTemperature: 0.0,
        uBorderThickness: 0.0,
        uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
        uSurfaceTension: 0.84,
        uChiselStrength: 2.97,
        uSSR_Strength: 0.05,
        uSSR_Falloff: 4.3,
        uSSR_Samples: 2,
        uParticleRate: 0.0,
        uParticleSize: 2.0,
        uParticleAdvection: 0.2,
        uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
        uCausticsIntensity: 3.2,
        uLightDepth: 0.4,
        uSurfaceDetailStrength: 0.01,
        uFlowSpeed: 8.0,
        uRippleStrength: 0.7,
        uRippleDamping: 0.98,
        uRippleSpeed: 0.7,
        uLight1Pos: new THREE.Vector3(0.8, 0.2, 0.7),
        uLight1Color: new THREE.Color(0.8, 0.4, 1.0),
        uLight2Pos: new THREE.Vector3(0.2, 0.8, 0.3),
        uLight2Color: new THREE.Color(0.0, 0.0, 0.0),
    },
    simParams: { waveDecay: 0.976, densityDissipation: 0.88, temperatureDissipation: 0.885 }
};
