import * as THREE from 'three';
import { Version } from '../types';

export const thermal: Version = {
    name: 'Thermal',
    uniforms: {
        uArtisticBlend: 0.1,
        uDisplacementScale: 0.1,
        uVelocityShiftScale: 0.003,
        uDensityShiftScale: 0.005,
        uWaterColor: new THREE.Color(0.2, 0.05, 0.0),
        uInkColor: new THREE.Color(1.0, 0.4, 0.1),
        uVolumeFactor: 0.4,
        uInkStrength: 2.0,
        uShininess: 200.0,
        uFresnelColor: new THREE.Color(1.0, 0.6, 0.3),
        uFresnelIntensity: 2.0,
        uGlowColor: new THREE.Color(1.0, 0.3, 0.0),
        uGlowPower: 3.0,
        uInkGeneration: 0.0,
        uWaveSize: 0.08,
        uWaveSteepness: 0.04,
        uWaveComplexity: 0.0,
        uWaveDetail: 0.0,
        uFeedRate: 0.0,
        uKillRate: 0.0,
        uVorticity: 5.0,
        uReactionForce: 0.0,
        uBuoyancy: 1.0,
        uAmbientTemperature: 0.0,
        uSplatTemperature: 0.5,
        uBorderThickness: 0.0,
        uBorderColor: new THREE.Color(0.0, 0.0, 0.0),
        uSurfaceTension: 0.1,
        uChiselStrength: 0.8,
        uSSR_Strength: 0.0,
        uSSR_Falloff: 1.0,
        uSSR_Samples: 0,
        uParticleRate: 0.0,
        uParticleSize: 2.0,
        uParticleAdvection: 0.2,
        uParticleColor: new THREE.Color(1.0, 1.0, 1.0),
        uCausticsIntensity: 0.0,
        uLightDepth: 0.5,
        uSurfaceDetailStrength: 0.1,
        uFlowSpeed: 1.0,
        uRippleStrength: 0.4,
        uRippleDamping: 0.98,
        uRippleSpeed: 0.5,
        uLight1Pos: new THREE.Vector3(0.5, 0.9, 0.5),
        uLight1Color: new THREE.Color(1.0, 0.6, 0.3),
        uLight2Pos: new THREE.Vector3(0.5, 0.1, 0.5),
        uLight2Color: new THREE.Color(1.0, 0.3, 0.0),
    },
    simParams: { waveDecay: 0.985, densityDissipation: 0.98, temperatureDissipation: 0.98 }
};
